# Generated by Django 4.2.7 on 2024-08-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_consent_pop',
            field=models.BooleanField(default=False),
        ),
    ]
