# Generated by Django 4.2.7 on 2024-09-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_consent_pop'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=500)),
            ],
        ),
    ]
