# Generated by Django 4.2.7 on 2024-12-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_queueinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='generation_quantity',
            field=models.IntegerField(default=3),
        ),
    ]
