# Generated by Django 4.2.7 on 2024-12-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_generation_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueinfo',
            name='topic',
            field=models.CharField(max_length=150),
        ),
    ]
