# Generated by Django 4.2.7 on 2025-01-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_queueinfo_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_cool_user',
            field=models.BooleanField(default=False),
        ),
    ]
