# Generated by Django 4.2.7 on 2025-01-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_is_cool_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_generation_quantity',
            field=models.IntegerField(default=3),
        ),
    ]
